TF vpc

diff --git a/.github/workflows/tf.yml b/.github/workflows/tf.yml
--- a/.github/workflows/tf.yml
+++ b/.github/workflows/tf.yml
@@ -1,68 +1,68 @@
-# name: Terraform Pipeline
+name: Terraform Pipeline
 
-# on:
-#   push:
-#     branches:
-#       - ft/develop
-#   workflow_dispatch:
-#     inputs:
-#       action:
-#         description: 'Choose the Terraform action (apply/destroy)'
-#         required: true
-#         default: 'apply'
+on:
+  push:
+    branches:
+      - ft/develop
+  workflow_dispatch:
+    inputs:
+      action:
+        description: 'Choose the Terraform action (apply/destroy)'
+        required: true
+        default: 'apply'
 
-# env:
-#   TF_LOG: INFO
-#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#   AWS_REGION: eu-west-1
+env:
+  TF_LOG: INFO
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  AWS_REGION: eu-west-1
 
-# jobs:
-#   terraform:
-#     name: Terraform Workflow
-#     runs-on: ubuntu-latest
-#     defaults:
-#       run:
-#         shell: bash
-#         working-directory: ./terraform/ecs-fargate
+jobs:
+  terraform:
+    name: Terraform Workflow
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./terraform/ecs-fargate
 
-#     steps:
-#       # Checkout repository
-#       - name: Checkout Repository
-#         uses: actions/checkout@v3
+    steps:
+      # Checkout repository
+      - name: Checkout Repository
+        uses: actions/checkout@v3
 
-#       # Setup Terraform
-#       - name: Setup Terraform
-#         uses: hashicorp/setup-terraform@v2
-#         with:
-#           terraform_version: 1.5.6
+      # Setup Terraform
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.5.6
 
-#       # Initialize Terraform
-#       - name: Terraform Init
-#         run: terraform init
+      # Initialize Terraform
+      - name: Terraform Init
+        run: terraform init
 
-#       # Validate Terraform
-#       - name: Terraform Validate
-#         run: terraform validate
+      # Validate Terraform
+      - name: Terraform Validate
+        run: terraform validate
 
-#       # Run Terraform Action
-#       - name: Run Terraform Action
-#         run: |
-#           action="${{ github.event.inputs.action }}"
-#           if [ -z "$action" ]; then
-#             echo "No action specified. Defaulting to 'apply'."
-#             action="apply"
-#           fi
+      # Run Terraform Action
+      - name: Run Terraform Action
+        run: |
+          action="${{ github.event.inputs.action }}"
+          if [ -z "$action" ]; then
+            echo "No action specified. Defaulting to 'apply'."
+            action="apply"
+          fi
 
-#           if [ "$action" == "apply" ]; then
-#             echo "Applying Terraform changes..."
-#             terraform plan -out=tfplan
-#             terraform apply -auto-approve tfplan
-#           elif [ "$action" == "destroy" ]; then
-#             echo "Destroying Terraform resources..."
-#             terraform destroy -auto-approve
-#           else
-#             echo "Invalid action. Only 'apply' or 'destroy' are supported."
-#             exit 1
-#           fi
+          if [ "$action" == "apply" ]; then
+            echo "Applying Terraform changes..."
+            terraform plan -out=tfplan
+            terraform apply -auto-approve tfplan
+          elif [ "$action" == "destroy" ]; then
+            echo "Destroying Terraform resources..."
+            terraform destroy -auto-approve
+          else
+            echo "Invalid action. Only 'apply' or 'destroy' are supported."
+            exit 1
+          fi
 
